---
title: "exercise-8 practice"
author: "Madison Downing"
date: "March 1, 2017"
output: html_document
---

### Exercise 1
```{r}
library(ggplot2)
dat <- read.csv("/home/eeb177-student/Desktop/eeb-177/lab-work/exercise-8/Rgraphics/dataSets/EconomistData.csv")
head(dat)
p1 <- ggplot(dat, aes(x = CPI, y = HDI))
p2 <- p1 + geom_point(aes(col = Region, size = HDI.Rank))
p2
```
# Exercise 2
```{r}
library(ggplot2)
p3 <- p2 + geom_smooth(method = "lm") + geom_line()
p3
?geom_line
```
# Exercise 3
```{r}
library(ggplot2)
p4 <- ggplot(dat, aes(x = CPI, y = HDI))
p5 <- p4 + geom_point(aes(col = Region))
p6 <- p5 + scale_x_continuous(name = "Corruption Perception Index") + scale_y_continuous(name = "Human Development Index")
cols <- c("Americas" = "red", "Asia Pacific" = "orange", "East EU Cemt Asia" = "yellow", "EU W. Europe" = "green", "MENA" = "blue", "SSA" = "purple")
p7 <- p6 + scale_color_manual(values = c("red", "orange", "yellow", "green", "blue", "purple"))
p7
```
# final exercise
```{r}
p7 + geom_smooth(method = "lm") + geom_line()
```